CREATE TABLE users (
    id BIGINT NOT NULL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(64) UNIQUE,
    password_hash TEXT NOT NULL
);

CREATE TABLE sessions (
    id INTEGER PRIMARY KEY,
    uid VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    user_id BIGINT NOT NULL REFERENCES users(id),
    last_ip TEXT NOT NULL,
    expires INTEGER NOT NULL
);